### ISSUE TITLE
windows session close - terminate called after throwing an instance of 'std::bad_function_call'

### ISSUE THREAD

**Issue by TheTechnobear** [davidmoreno/rtpmidid#14]
````
[2019-11-23T14:27:12Z] [main.cpp:47] (C) 2019 David Moreno Montero <dmoreno@coralbits.com>
[2019-11-23T14:27:12Z] [mdns_rtpmidi.cpp:85] watch_new 5 1
[2019-11-23T14:27:12Z] [rtpserver.cpp:84] Listening RTP MIDI connections at 0.0.0.0:5004, with name: 'patchbox'
[2019-11-23T14:27:12Z] [mdns_rtpmidi.cpp:280] (Browser) NEW: service 'bear' of type '_apple-midi._udp' in domain 'local'
[2019-11-23T14:27:12Z] [mdns_rtpmidi.cpp:294] (Browser) CACHE_EXHAUSTED
[2019-11-23T14:27:12Z] [mdns_rtpmidi.cpp:229] Service 'bear' of type '_apple-midi._udp' in domain 'local'
[2019-11-23T14:27:12Z] [mdns_rtpmidi.cpp:250] 	bear.local:5004 (192.168.1.94)
	interface=2
	TXT=
	cookie is 0
	is_local: false
	our_own: false
	wide_area: false
	multicast: true
	cached: true
[2019-11-23T14:27:12Z] [rtpmidid.cpp:191] New alsa port: 1, connects to 192.168.1.94:5004 (bear)
[2019-11-23T14:27:12Z] [mdns_rtpmidi.cpp:280] (Browser) NEW: service 'patchbox' of type '_apple-midi._udp' in domain 'local'
[2019-11-23T14:27:13Z] [mdns_rtpmidi.cpp:58] Service '/Client4/EntryGroup1' successfully established
[2019-11-23T14:27:13Z] [mdns_rtpmidi.cpp:225] Received own announcement
[2019-11-23T14:27:13Z] [mdns_rtpmidi.cpp:294] (Browser) ALL_FOR_NOW
[2019-11-23T14:27:17Z] [mdns_rtpmidi.cpp:280] (Browser) NEW: service 'PERRO' of type '_apple-midi._udp' in domain 'local'
[2019-11-23T14:27:17Z] [mdns_rtpmidi.cpp:229] Service 'PERRO' of type '_apple-midi._udp' in domain 'local'
[2019-11-23T14:27:17Z] [mdns_rtpmidi.cpp:250] 	PERRO.local:5004 (192.168.1.13)
	interface=2
	TXT=
	cookie is 0
	is_local: false
	our_own: false
	wide_area: false
	multicast: true
	cached: true
[2019-11-23T14:27:17Z] [rtpmidid.cpp:191] New alsa port: 2, connects to 192.168.1.13:5004 (PERRO)
[2019-11-23T14:27:27Z] [mdns_rtpmidi.cpp:289] (Browser) REMOVE: service 'PERRO' of type '_apple-midi._udp' in domain 'local'
terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call
Aborted
````

caused by 
/home/patch/projects/rtpmidid/src/mdns_rtpmidi.cpp:290

presumably bad function pointed.
````
Catchpoint 1 (exception thrown), 0x76db4948 in __cxa_throw () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
(gdb) bt
#0  0x76db4948 in __cxa_throw () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
#1  0x76ddd680 in std::__throw_bad_function_call() () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
#2  0x000d822c in std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (this=0x7efff058, __args#0="PERRO") at /usr/include/c++/8/bits/std_function.h:686
#3  0x000d54a0 in browse_callback (b=0x156d88, interface=2, protocol=0, event=AVAHI_BROWSER_REMOVE, name=0x15b804 "PERRO", type=0x15b810 "_apple-midi._udp", domain=0x15b828 "local", 
    flags=AVAHI_LOOKUP_RESULT_MULTICAST, userdata=0x7efff030) at /home/patch/projects/rtpmidid/src/mdns_rtpmidi.cpp:290
#4  0x76e90f68 in avahi_service_browser_event () from /usr/lib/arm-linux-gnueabihf/libavahi-client.so.3
Backtrace stopped: Cannot access memory at address 0x6c69613e
(gdb) 

````

**Comment by TheTechnobear** [comment]
commit stops crashing, and raises TODO to close the rest of the session (eg. dangling alsa session)
